Enhancement: display an error msg when a video does not start
To start video playback, user must first interact with the page :
NotAllowedError: play() failed because the user didn't interact with the document first. https://goo.gl/xX8pDD